package com.webservices.restapi.entity;

import java.io.Serializable;


import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import io.swagger.annotations.ApiModelProperty;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

@Data
@AllArgsConstructor
@NoArgsConstructor
@Entity
@Getter
@Setter
@ToString
@Table(name = "foodProductTable")
public class FoodProduct implements Serializable {


	private static final long serialVersionUID = -6599475578679981537L;

	@Id
	@GeneratedValue
	@ApiModelProperty(value = "autogenerated id")
	private int id;
	
	@ApiModelProperty(value= "This is product name")
	private String name;
	@ApiModelProperty(value="This is product quantity")
	private int quantity;

	@ApiModelProperty(value="This is product price")
	private double price;

//	public FoodProduct(String name, int quantity, double price) {
//		super();
//		this.name = name;
//		this.quantity = quantity;
//		this.price = price;
//	}

	

	
}
